### ISSUE TITLE
Tutorial on Classical-Quantum transfer learning

### ISSUE THREAD

**Issue by Gopal-Dahale** [Gopal-Dahale/qml-hep-lhc#2]
## Aim
Develop a tutorial on classical quantum transfer learning in TensorFlow-quantum on MNIST Dataset.

## Details
The tutorial should use a classical pretrained model with a trainable quantum circuit as the head. One can take inspiration from [PennyLane's tutorial](https://pennylane.ai/qml/demos/tutorial_quantum_transfer_learning.html).

## Resources
- A classical-quantum model definition is already [present](https://github.com/Gopal-Dahale/qml-hep-lhc/blob/main/qml_hep_lhc/models/quantum/resnetq50.py) in the repo. You can develop this or create a new model definition at the same directory level.
- See the [tutorials](https://github.com/Gopal-Dahale/qml-hep-lhc/tree/main/notebooks/Tutorials) to understand how things work.

**Comment by Om12Dahale** [comment]
@Gopal-Dahale Hi sir looking forward to contribute, please assign this task to me.
